name: TEST - CI/CD Pipeline with Threagile and OPA

on:
  push:
    branches:
      - main
    paths:
      - 'threagile.yaml'
      - 'policies/**'
  pull_request:
  workflow_dispatch:

jobs:
  threagile_analysis:
    runs-on: [Linux]
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: true

      - name: Run Threagile
        id: threagile
        uses: threagile/run-threagile-action@v1
        with:
          model-file: 'threagile.yaml'

      - name: Verify Generated Files
        run: |
          echo "Verifying Threagile output..."
          ls -la threagile/output
          cat threagile/output/stats.json
          cat threagile/output/risks.json

      - name: Archive Results
        uses: actions/upload-artifact@v3
        with:
          name: threagile-report
          path: threagile/output

      - name: Commit & Push Report and DFD Diagram
        run: |
          git config --local user.email "threagile@example.com"
          git config --local user.name "Threagile"
          git add threagile/output/*
          if ! git diff --cached --quiet; then
            git commit -m "Update threat model reports and data-flow diagrams by Threagile"
            git push origin HEAD:${{ github.ref }}
          else
            echo "No changes to commit."
          fi

  opa_policy_check:
    runs-on: [Linux]
    needs: threagile_analysis
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Open Policy Agent
        uses: open-policy-agent/setup-opa@v2.2.0
        with:
          version: '0.70.0'

      - name: Verify OPA Installation
        run: opa version

      - name: Run OPA Policy Check
        run: |
          # Ensure jq is installed
          if ! command -v jq &> /dev/null; then
            echo "Installing jq..."
            sudo apt-get update && sudo apt-get install -y jq
          fi

          check_opa() {
            local input_file=$1
            echo "Evaluating policy for $input_file"

            opa eval --data policies/vulnerabilities/vulnerabilities.rego \
              --input "$input_file" "data.policies.vulnerabilities.deny" --format=json > opa_result.json

            local deny_count=$(jq '.result[0].expressions[0].value | length' opa_result.json)
            echo "Deny Count: $deny_count"

            if [ "$deny_count" -gt 0 ]; then
              echo "OPA Policy Check Failed: Detected $deny_count issues."
              jq -r '.result[0].expressions[0].value[]' opa_result.json
              return 1
            else
              echo "OPA Policy Check Passed: No high-severity vulnerabilities detected."
              return 0
            fi
          }

          # Test 1: Valid Threagile output
          echo "Running Test 1: Valid Threagile artifacts..."
          cp threagile/output/success.json input.json
          check_opa input.json || exit 1

          # Test 2: Missing Threagile output
          echo "Running Test 2: Missing Threagile artifacts..."
          echo "{}" > input.json
          check_opa input.json || exit 1

          # Test 3: High/Critical vulnerabilities
          echo "Running Test 3: High/Critical vulnerabilities present..."
          cp threagile/output/stats.json input.json
          check_opa input.json || exit 1
